// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: logs.proto
#ifndef GRPC_logs_2eproto__INCLUDED
#define GRPC_logs_2eproto__INCLUDED

#include "logs.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace logs {

class LogService final {
 public:
  static constexpr char const* service_full_name() {
    return "logs.LogService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::logs::LogMessage>> StreamLogs(::grpc::ClientContext* context, const ::logs::LogRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::logs::LogMessage>>(StreamLogsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::logs::LogMessage>> AsyncStreamLogs(::grpc::ClientContext* context, const ::logs::LogRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::logs::LogMessage>>(AsyncStreamLogsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::logs::LogMessage>> PrepareAsyncStreamLogs(::grpc::ClientContext* context, const ::logs::LogRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::logs::LogMessage>>(PrepareAsyncStreamLogsRaw(context, request, cq));
    }
    // Server Streaming RPC
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void StreamLogs(::grpc::ClientContext* context, const ::logs::LogRequest* request, ::grpc::ClientReadReactor< ::logs::LogMessage>* reactor) = 0;
      // Server Streaming RPC
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::logs::LogMessage>* StreamLogsRaw(::grpc::ClientContext* context, const ::logs::LogRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::logs::LogMessage>* AsyncStreamLogsRaw(::grpc::ClientContext* context, const ::logs::LogRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::logs::LogMessage>* PrepareAsyncStreamLogsRaw(::grpc::ClientContext* context, const ::logs::LogRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::logs::LogMessage>> StreamLogs(::grpc::ClientContext* context, const ::logs::LogRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::logs::LogMessage>>(StreamLogsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::logs::LogMessage>> AsyncStreamLogs(::grpc::ClientContext* context, const ::logs::LogRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::logs::LogMessage>>(AsyncStreamLogsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::logs::LogMessage>> PrepareAsyncStreamLogs(::grpc::ClientContext* context, const ::logs::LogRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::logs::LogMessage>>(PrepareAsyncStreamLogsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void StreamLogs(::grpc::ClientContext* context, const ::logs::LogRequest* request, ::grpc::ClientReadReactor< ::logs::LogMessage>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::logs::LogMessage>* StreamLogsRaw(::grpc::ClientContext* context, const ::logs::LogRequest& request) override;
    ::grpc::ClientAsyncReader< ::logs::LogMessage>* AsyncStreamLogsRaw(::grpc::ClientContext* context, const ::logs::LogRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::logs::LogMessage>* PrepareAsyncStreamLogsRaw(::grpc::ClientContext* context, const ::logs::LogRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_StreamLogs_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status StreamLogs(::grpc::ServerContext* context, const ::logs::LogRequest* request, ::grpc::ServerWriter< ::logs::LogMessage>* writer);
    // Server Streaming RPC
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamLogs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamLogs() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StreamLogs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamLogs(::grpc::ServerContext* /*context*/, const ::logs::LogRequest* /*request*/, ::grpc::ServerWriter< ::logs::LogMessage>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamLogs(::grpc::ServerContext* context, ::logs::LogRequest* request, ::grpc::ServerAsyncWriter< ::logs::LogMessage>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StreamLogs<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_StreamLogs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamLogs() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::logs::LogRequest, ::logs::LogMessage>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::logs::LogRequest* request) { return this->StreamLogs(context, request); }));
    }
    ~WithCallbackMethod_StreamLogs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamLogs(::grpc::ServerContext* /*context*/, const ::logs::LogRequest* /*request*/, ::grpc::ServerWriter< ::logs::LogMessage>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::logs::LogMessage>* StreamLogs(
      ::grpc::CallbackServerContext* /*context*/, const ::logs::LogRequest* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_StreamLogs<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_StreamLogs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamLogs() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StreamLogs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamLogs(::grpc::ServerContext* /*context*/, const ::logs::LogRequest* /*request*/, ::grpc::ServerWriter< ::logs::LogMessage>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamLogs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamLogs() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_StreamLogs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamLogs(::grpc::ServerContext* /*context*/, const ::logs::LogRequest* /*request*/, ::grpc::ServerWriter< ::logs::LogMessage>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamLogs(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamLogs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamLogs() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->StreamLogs(context, request); }));
    }
    ~WithRawCallbackMethod_StreamLogs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamLogs(::grpc::ServerContext* /*context*/, const ::logs::LogRequest* /*request*/, ::grpc::ServerWriter< ::logs::LogMessage>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* StreamLogs(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_StreamLogs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_StreamLogs() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::logs::LogRequest, ::logs::LogMessage>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::logs::LogRequest, ::logs::LogMessage>* streamer) {
                       return this->StreamedStreamLogs(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_StreamLogs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StreamLogs(::grpc::ServerContext* /*context*/, const ::logs::LogRequest* /*request*/, ::grpc::ServerWriter< ::logs::LogMessage>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedStreamLogs(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::logs::LogRequest,::logs::LogMessage>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_StreamLogs<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_StreamLogs<Service > StreamedService;
};

}  // namespace logs


#endif  // GRPC_logs_2eproto__INCLUDED
