// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: logs.proto

#include "logs.pb.h"
#include "logs.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace logs {

static const char* LogService_method_names[] = {
  "/logs.LogService/StreamLogs",
};

std::unique_ptr< LogService::Stub> LogService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< LogService::Stub> stub(new LogService::Stub(channel, options));
  return stub;
}

LogService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_StreamLogs_(LogService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientReader< ::logs::LogMessage>* LogService::Stub::StreamLogsRaw(::grpc::ClientContext* context, const ::logs::LogRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::logs::LogMessage>::Create(channel_.get(), rpcmethod_StreamLogs_, context, request);
}

void LogService::Stub::async::StreamLogs(::grpc::ClientContext* context, const ::logs::LogRequest* request, ::grpc::ClientReadReactor< ::logs::LogMessage>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::logs::LogMessage>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamLogs_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::logs::LogMessage>* LogService::Stub::AsyncStreamLogsRaw(::grpc::ClientContext* context, const ::logs::LogRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::logs::LogMessage>::Create(channel_.get(), cq, rpcmethod_StreamLogs_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::logs::LogMessage>* LogService::Stub::PrepareAsyncStreamLogsRaw(::grpc::ClientContext* context, const ::logs::LogRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::logs::LogMessage>::Create(channel_.get(), cq, rpcmethod_StreamLogs_, context, request, false, nullptr);
}

LogService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LogService_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< LogService::Service, ::logs::LogRequest, ::logs::LogMessage>(
          [](LogService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::logs::LogRequest* req,
             ::grpc::ServerWriter<::logs::LogMessage>* writer) {
               return service->StreamLogs(ctx, req, writer);
             }, this)));
}

LogService::Service::~Service() {
}

::grpc::Status LogService::Service::StreamLogs(::grpc::ServerContext* context, const ::logs::LogRequest* request, ::grpc::ServerWriter< ::logs::LogMessage>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace logs

